In [2]:
import pandas as pd
import os

In [3]:
def load_tsv_data(tsv_path: str) -> pd.DataFrame:
    """Load TSV data file with standard column names."""
    df = pd.read_csv(tsv_path, sep="\t", header=None, keep_default_na=False)
    df.columns = ["idx", "label", "sentence", "subject_text", "object_text", "subject_type", "object_type", "subject_group", "object_group", "label_choices"]
    return df

train_pth = "data/train.out"
test_pth = "data/test.out"
validation_pth = "data/test.out"
df_train = load_tsv_data(train_pth)
df_test = load_tsv_data(test_pth)
df_val = load_tsv_data(validation_pth)

In [8]:
df_train.head()

,idx,label,sentence,subject_text,object_text,subject_type,object_type,subject_group,object_group,label_choices
0,0,LOCATION_OF,We tested the hsp-70 promoter as well as a pro...,head,reporter gene,Body Location or Region,Gene or Genome,Anatomy,Genes and Molecular Sequences,location_of
1,1,PROCESS_OF,A patient who had had a functioning peritoneov...,superior vena cava syndrome,patient,Disease or Syndrome,Human,Disorders,Living Beings,process_of; affects
2,2,None,Antiestrogenic effect of clomiphene in the hum...,Antiestrogenic,clomiphene,Pharmacologic Substance,Organic Chemical,Chemicals and Drugs,Chemicals and Drugs,stimulates; coexists_with; inhibits; interacts...
3,3,None,These results demonstrate that [3H]BTX-B can b...,sodium channel,antiarrhythmic drugs,"Amino Acid, Peptide, or Protein",Pharmacologic Substance,Chemicals and Drugs,Chemicals and Drugs,inhibits; compared_with; interacts_with; stimu...
4,4,PART_OF,The main site for ROS production is the respir...,respiratory chain,mitochondria,Cell Component,Cell Component,Anatomy,Anatomy,part_of; location_of

In [4]:
print(len(df_train), print(len(df_test)))

3548
8187 None

In [5]:
labels = df_train['label'].unique()
labels.sort()
labels

array(['ADMINISTERED_TO', 'AFFECTS', 'ASSOCIATED_WITH', 'AUGMENTS',
       'CAUSES', 'COEXISTS_WITH', 'COMPARED_WITH', 'DIAGNOSES',
       'DISRUPTS', 'INHIBITS', 'INTERACTS_WITH', 'ISA', 'LOCATION_OF',
       'None', 'PART_OF', 'PRECEDES', 'PREDISPOSES', 'PREVENTS',
       'PROCESS_OF', 'PRODUCES', 'STIMULATES', 'TREATS', 'USES'],
      dtype=object)

In [6]:
df_test.head()

,idx,label,sentence,subject_text,object_text,subject_type,object_type,subject_group,object_group,label_choices
0,0,INHIBITS,"Here we show that chymases, which are chymotry...",chymases,scatter factor,"Amino Acid, Peptide, or Protein","Amino Acid, Peptide, or Protein",Chemicals and Drugs,Chemicals and Drugs,inhibits; compared_with; isa; interacts_with; ...
1,1,PART_OF,BAFF-R expression was found only in B-cell lym...,BAFF-R,lymphoplasmacytic lymphoma,Gene or Genome,Neoplastic Process,Genes and Molecular Sequences,Disorders,disrupts; augments; affects; part_of; prevents...
2,2,ISA,X-linked adrenoleukodystrophy (X-ALD) is a per...,tetracosanoic acid,very long chain fatty acids (VLCFA),Lipid,Lipid,Chemicals and Drugs,Chemicals and Drugs,isa; stimulates; inhibits; coexists_with
3,3,INHIBITS,Removal of sialic acids by C. perfringens sial...,sialidase,sialic acids,"Amino Acid, Peptide, or Protein",Carbohydrate,Chemicals and Drugs,Genes and Molecular Sequences,interacts_with; stimulates; inhibits; coexists...
4,4,None,BAP31 and its caspase cleavage product regulat...,BAP31,integrin,Gene or Genome,"Amino Acid, Peptide, or Protein",Genes and Molecular Sequences,Chemicals and Drugs,inhibits; compared_with; interacts_with; produ...